### ISSUE TITLE
Print Ignored in __main__.py

### ISSUE THREAD

**Issue by OseSem** [eludris-community/velum#14]
You guys are ignoring `T201` (Allowing printing in scripts) in `__main__.py`, but this could be ignored by using something like `logger.debug` with a null handler so it only does it when turned on in the project that uses logging with velum or making a rich console and printing it via that.

I could help providing any of this code.

**Comment by ooliver1** [comment]
The reason for `__main__.py` is to create and print a session token. There is no need to use `logging` for this as this script is entirely optional - `python -m velum <identifier> <password>`. The token is not debugging output, it is the whole reason of using the script in the first place.
